apiVersion: v1
kind: SystemApplication
metadata:
  namespace: kube-system
  name: logging-app
  repository: gravitational.io
  resourceVersion: 0.0.4
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-bootstrap
      spec:
        template:
          metadata:
            name: logging-app-bootstrap
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:0.0.1
                command: ["/usr/local/bin/kubectl", "apply", "-f", "/var/lib/gravity/resources/resources.yaml"]
  update:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-update
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 100
        template:
          metadata:
            name: logging-app-update
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: log-hook:0.0.1
                args: ["update"]
  rollback:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-rollback
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 100
        template:
          metadata:
            name: logging-app-rollback
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: log-hook:0.0.1
                args: ["rollback"]
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-uninstall
      spec:
        template:
          metadata:
            name: logging-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:0.0.1
                command: ["/usr/local/bin/kubectl", "delete", "-f", "/var/lib/gravity/resources/resources.yaml"]
