apiVersion: v1
kind: SystemApplication
metadata:
  namespace: kube-system
  name: logging-app
  resourceVersion: 0.0.2
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-bootstrap
      spec:
        template:
          metadata:
            name: logging-app-bootstrap
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: hook:0.0.1
                command: ["/usr/local/bin/kubectl", "apply", "-f", "/var/lib/gravity/resources/resources.yaml"]

  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-uninstall
      spec:
        template:
          metadata:
            name: logging-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: hook:0.0.1
                command: ["/usr/local/bin/kubectl", "delete", "-f", "/var/lib/gravity/resources/resources.yaml"]
