apiVersion: bundle.gravitational.io/v2
kind: SystemApplication
metadata:
  name: logging-app
  resourceVersion: "0.0.0"
  namespace: kube-system
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-bootstrap
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: logging-app-bootstrap
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: log-hook:0.0.1
                args: ["bootstrap"]
  update:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-update
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: logging-app-update
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: log-hook:0.0.1
                args: ["update"]
  rollback:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-rollback
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: logging-app-rollback
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: log-hook:0.0.1
                args: ["rollback"]
  uninstall:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: logging-app-uninstall
      spec:
        template:
          metadata:
            name: logging-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:0.0.1
                command: ["/usr/local/bin/kubectl", "delete", "-f", "/var/lib/gravity/resources/resources.yaml"]
