apiVersion: v1
kind: Service
metadata:
  name: log-collector
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - name: rsyslog-udp
      protocol: UDP
      port: 514
      targetPort: 5514
    - name: rsyslog-tcp
      protocol: TCP
      port: 514
      targetPort: 5514
    - name: web-tail
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    role: log-collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-log-collector-config
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: log-collector
    name: log-collector
    version: v1
  name: log-collector
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      role: log-collector
      version: v1
  template:
    metadata:
      labels:
        role: log-collector
        version: v1
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: log-collector
          image: log-collector:latest
          ports:
            - name: udp
              protocol: UDP
              containerPort: 514
            - name: tcp
              protocol: TCP
              containerPort: 514
            - name: web-tail
              protocol: TCP
              containerPort: 8083
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: extra-log-collector-config
              mountPath: /etc/rsyslog.d
      volumes:
        - name: extra-log-collector-config
          configMap:
            name: extra-log-collector-config
        - name: varlog
          hostPath:
            path: /var/log
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: log-forwarder
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: log-forwarder
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: log-forwarder
          image: log-forwarder:latest
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: extdockercontainers
              mountPath: /ext/docker/containers
            - name: gravitysite
              mountPath: /var/lib/gravity/site
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: extdockercontainers
          hostPath:
            path: /ext/docker/containers
        - name: gravitysite
          hostPath:
            path: /var/lib/gravity/site
